apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      serviceAccountName: doclayout-sa
      containers:
      - name: mlflow-server
        image: python:3.9-slim
        command:
          - /bin/bash
          - -c
          - |
            pip install mlflow boto3
            mlflow server \
              --backend-store-uri /mlflow/store \
              --default-artifact-root s3://your-doclayout-bucket/experiments/artifacts \
              --host 0.0.0.0 \
              --port 5000
        ports:
        - containerPort: 5000
        env:
        - name: AWS_DEFAULT_REGION
          value: "us-west-2"
        volumeMounts:
        - name: mlflow-storage
          mountPath: /mlflow
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  selector:
    app: mlflow-server
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer